config/routes.rb
Rails.application.routes.draw do

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  get "/log_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get 'transactions/new'

  get "mapmyride" => "vehicles#map"

  root 'welcome#index'

  get 'users/show'

  get 'users/edit'

  get 'users/update'

  get 'users/destroy'

  resources :vehicles

  resources :reservations

  resources :transactions, only: [:new, :create]

  resources :users, only: [:show, :edit, :update, :destroy]

  
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  
  get 'tags/:tag', to: 'welcome#index', as: "tag"

  get "/vehicle/payment", to: "vehicle#payment"

end

app/models/user.rb
class User < ActiveRecord::Base
  
  	include Clearance::User
    
    has_many :reservations 
    has_many :vehicles
    has_many :authentications, :dependent => :destroy

    mount_uploader :pic, ImageUploader2

  def self.create_with_auth_and_hash(authentication,auth_hash)
    create! do |u|
      u.first_name = auth_hash["info"]["name"]
      u.email = auth_hash["extra"]["raw_info"]["email"] || "#{auth_hash["info"]["name"]}@tempmail.com"
      u.pic = auth_hash["info"]["image"]
      u.password = SecureRandom.hex(6)
      u.authentications<<(authentication)
    end
  end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end

  def password_optional?
    true
  end

  # def cart_total_price
  # total_price = 0
  # get_cart_reservations.each { |reservation| total_price += reservation.total_price }
  # total_price
  # end

  # def get_cart_reservations
  #   cart_ids = $redis.smembers "cart#{id}"
  #   Reservation.find(cart_ids)
  # end

  # def purchase_cart_reservations!
  #   get_cart_reservations.each { |reservation| purchase(reservation) }
  #   $redis.del "cart#{id}"
  # end

  def purchase(reservation)
    reservations << reservation unless purchase?(reservation)
  end

  def purchase?(reservation)
    reservations.include?(reservation)
  end

end

app/controllers/clearance/users_controller.rb
class Clearance::UsersController < Clearance::BaseController
  if respond_to?(:before_action)
    before_action :redirect_signed_in_users, only: [:create, :new]
    skip_before_action :require_login, only: [:create, :new], raise: false
    skip_before_action :authorize, only: [:create, :new], raise: false
  else
    before_filter :redirect_signed_in_users, only: [:create, :new]
    skip_before_filter :require_login, only: [:create, :new], raise: false
    skip_before_filter :authorize, only: [:create, :new], raise: false
  end

  def new
    @user = user_from_params
    render template: "users/new"
  end

  def create
    @user = user_from_params

    if @user.save
      sign_in @user
      redirect_back_or url_after_create
    else
      render template: "users/new"
    end
  end

  private

  def avoid_sign_in
    warn "[DEPRECATION] Clearance's `avoid_sign_in` before_filter is " +
      "deprecated. Use `redirect_signed_in_users` instead. " +
      "Be sure to update any instances of `skip_before_filter :avoid_sign_in`" +
      " or `skip_before_action :avoid_sign_in` as well"
    redirect_signed_in_users
  end

  def redirect_signed_in_users
    if signed_in?
      redirect_to Clearance.configuration.redirect_url
    end
  end

  def url_after_create
    Clearance.configuration.redirect_url
  end

  def user_from_params
    email = user_params.delete(:email)
    pic = user_params.delete(:pic)
    first_name = user_params.delete(:first_name)
    password = user_params.delete(:password)

    Clearance.configuration.user_model.new(user_params).tap do |user|
      user.email = email
      user.pic = pic
      user.first_name = first_name
      user.password = password
    end
  end

  def user_params
    params[Clearance.configuration.user_parameter] || Hash.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
    @bookings = Reservation.all.order('created_at DESC').paginate(page: params[:page], per_page: 2)
    @for_rent = current_user.vehicles.order('created_at DESC').paginate(page: params[:page], per_page: 2)

    # @for_rent = Vehicle.all.order('created_at DESC').paginate(page: params[:page], per_page: 2)
  end

  def edit
  end

  def update
  	@user = User.find(params[:id])
  	@user.update(user_params)

      if @user.save
        redirect_to user_path(@user.id)
      else
        redirect "/"
    end

  end

  def destroy
  end
end

private 
  def user_params 
    params.require(:user).permit(:first_name, :pic) 
  end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
    <div class="fname-field">
      <%= form.label "Username" %>
      <%= form.text_field :first_name, type: 'first_name' %>
    </div>
    <br>
    <div class="text-field">
      <%= form.label :email %>
      <%= form.text_field :email, type: 'email' %>
    </div>
    <br>
    <div class="password-field">
      <%= form.label :password %>
      <%= form.password_field :password %>
    </div>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
<div id="main" class="wrapper style1">
          <div class="container">
            <header class="major">
              <h2>Sign up and ignite the spark</h2>
            </header>
            <div class="row 150%">
              <div class="8u 12u$(medium)">

                <!-- Content -->
                  <section id="content">
                    <span class="image fit main"><%=image_tag "signup.jpg"%></span>
                       <h3>Hello and welcome to OpenThrottle, please enter your info below:</h3>
                   <%= form_for @user do |form| %>
                   <%= render partial: '/users/form', object: form %>
                 <div class="submit-field">
                 <br>
                   <%= form.submit %>
                   <% end %>
                  </section>

              </div>
              <div class="4u$ 12u$(medium)">

                <!-- Sidebar -->
                  <section id="sidebar">
                    <section>
                      <h3>You can also sign-up with Facebook in 5 seconds!</h3>
                      <%= button_to 'Facebook Sign-Up', "/auth/facebook" %>
                    </section>
                    <hr />
                    <section>
                      <h3>Already have a user account? Sign-in here!</h3>
                      <div class="button"><%= link_to t(".sign_in"), sign_in_path %></div>
                      <footer>
                    </section>
                  </section>

              </div>
            </div>
          </div>
        </div>
</div>



                

app/views/users/show.html.erb
<div id="main" class="wrapper style1">
	<div class="container">
		<header class="major">
			<h2>Your Profile</h2>
			<p>Hello <%= @user.first_name %>, and welcome to OpenThrottle!</p>
		</header>
		<div class="row 150%">
			<div class="4u 12u$(medium)">

				<!-- Sidebar -->
				<section id="sidebar">
					<section>
						<h3>Upload a profile picture</h3>
						<p>Give some pep to your profile, upload a pic of you on your ride of choice!</p>
						<%= form_for @user, url: user_path(@user.id) do |x| %>
						<footer>
							<ul class="actions">
								<li><%= x.file_field :pic %></li>
							</ul>
						</footer>

						<%= x.submit "Upload" %>
						<% end %>

					</section>
					<hr />
					<section>
						<a href="#" class="image fit"><%= image_tag @user.pic.to_s %></a>
						<hr />
						<%= will_paginate @bookings %>
						<h3>Your bookings</h3>
						<div class="8u$ 12u$(medium) important(medium)">
							<% @bookings.each do |booking| %> 
							<section id="content">
								<% if booking.user_id = current_user.id %>
								<span><h6>Your booked this motorbike on: <%= booking.created_at %></h6></span>
								<ul>
									<li><strong>Check-in:</strong> <%= booking.check_in_date %></li>
									<li><strong>Check-out:</strong> <%= booking.check_out_date%> </li>
									<li><strong>Price Paid:</strong> USD <%= booking.total_price%></li>
								</ul>
								<%else%>
								You have no bookings at the moment! Why don't you check out the bikes for rent?
								<p><div class="button"><%= link_to 'See all the vehicles for rent', vehicles_path %></div></p>
								<%break%>
								<%end%>
								<%end%>
							</section>
						</section>
					</section>

				</div>
				<div class="8u$ 12u$(medium) important(medium)">

					<!-- Content -->
					<section id="content">
						<a href="#" class="image fit"><%=image_tag "picsunset.jpg" %></a>

						<%= will_paginate @for_rent %>
						<h2>Your vehicles for rent</h2>
							<% if @for_rent.count  1 %>
							

								<% @for_rent.each do |for_rent| %> 

									<section id="content">
									
									<span class="image left"><%=image_tag for_rent.image.to_s %></span>
									<ul>
										<ul><strong>Description:</strong> <%= for_rent.description %></ul>
										<ul><strong>Location:</strong> <%= for_rent.city%> </ul>
										<ul><strong>Rental price per day:</strong> USD <%= for_rent.price_per_day%></ul>
									</ul>
									<h3><%= button_to 'See this listing now!', vehicle_path(for_rent), method: "get"%></h3>
									<span><h6>Your created this listing on: <%= for_rent.created_at %></h6></span>
									<br>
									<br>
								<%end%>
								<div class="button"><%= link_to 'Have a new vehicle for rent ? Create a listing here!', new_vehicle_path %></div>
							<%else%>
								You have no vehicle for rent at the moment! Why don't you create one now?
								<p><div class="button"><%= link_to 'Create a new vehicle for rent', new_vehicle_path %></div></p>
						
							<%end%>
							

							<hr />
						</div>
					</div>
				</div>
			</div>

app/views/users/test.html.erb
<h1>test</h1>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>