config/routes.rb
Rails.application.routes.draw do

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  get "/log_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get 'transactions/new'

  get "mapmyride" => "vehicles#map"

  root 'welcome#index'

  get 'users/show'

  get 'users/edit'

  get 'users/update'

  get 'users/destroy'

  resources :vehicles

  resources :reservations

  resources :transactions, only: [:new, :create]

  resources :users, only: [:show, :edit, :update, :destroy]

  
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  
  get 'tags/:tag', to: 'welcome#index', as: "tag"

  get "/vehicle/payment", to: "vehicle#payment"

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@vehicle = Vehicle.new
  	@vehicles= Vehicle.all
  	@lastvehicle = Vehicle.last
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
			<!-- Banner -->
				<section id="banner">
					<div class="content">
						<header>
							<h2></h2>
							<p>Make money with your motorbike.<br /> 
							 Borrow your dream ride.<br />
							 Go for a ride. Now.</p>
						</header>
						<span class="image"><%=image_tag "pic01.jpg" %></span>
					</div>
					<a href="#one" class="goto-next scrolly">Next</a>
				</section>

			<!-- One -->
				<section id="one" class="spotlight style1 bottom">
					<span class="image fit main"><%=image_tag "pic02.jpg"%></span>
					<div class="content">
						<div class="container">
							<div class="row">
								<div class="4u 12u$(medium)">
									<header>
										<h2>Need a Ride? Stop Searching. Start Riding.</h2>

										<p>OpenThrottle is the world leading peer-to-peer motorcycle rental.</p>
									</header>
								</div>
								<div class="4u 12u$(medium)">
									<p>Most motorcyclists use the word "freedom" to describe the feeling they get when they ride. Open roads, wind in your hair, escaping into the grandeur of mountains and canyons. Freedom is not just being without constraints, but being motivated to shed those constraints when you ride. A motorcycle isn't something you have, it's something you do.</p>
								</div>
								<div class="4u$ 12u$(medium)">
									<p>OpenThrottle aims at empowering riders everywhere to share their love of riding with their peers. Riders often say that once you ride, you experience complete presence in the moment.</p><p> So go for it, rent a new motorbike and go for that ride. Rent your own motorbike and make extra money. Open the throttle. You're here.</p>
								</div>
							</div>
						</div>
					</div>
					<a href="#two" class="goto-next scrolly">Next</a>
				</section>

			<!-- Two -->
				<section id="two" class="spotlight style2 right">
					<span class="image fit main"><%=image_tag "pic03.jpg" %></span>
					<div class="content">
						<header>
							<h2>Make money with your motorbike</h2>
							<p>Your bike sits idle. Make it roam for you and earn cash.</p>
						</header>
						<p>Let' be honest, even though we'd like it, we can't be riding our bikes all the time. Harness the power of the web and rent it out, peer-to-peer style.</p> <p> People like you are on the lookout for good clean fun, and would love to pay you to rent your ride for a day or two. 	</p>
						<ul class="actions">
							<li><div class="button"><%= link_to "Sounds great, I\'m in", sign_up_path %></div></li>
						</ul>
					</div>
					<a href="#three" class="goto-next scrolly">Next</a>
				</section>

			<!-- Three -->
				<section id="three" class="spotlight style3 left">
					<span class="image fit main bottom"><%=image_tag "pic04.jpg" %></span>
					<div class="content">
						<header>
							<h2>Borrow a bike</h2>
							<p>Rent the motorcycle of your dreams from people who really care</p>
						</header>
						<p>Have you ever wished you could snap a finger and instantly be on the road with your buddies? Well, we're not there *yet* but pretty damn close!</p><p> With Open Throttle, you choose your ride, book it, and you're good to go.</p><p>Best of all, the people you borrow the bike from are just like you and will care all the way.</p>
						<ul class="actions">
							<li><%= link_to 'Show all bikes for rent', vehicles_path, :class => "button" %></li>
						</ul>
					</div>
					<a href="#four" class="goto-next scrolly">Next</a>
				</section>

			<!-- Four -->
				<section id="four" class="wrapper style1 special fade-up">
					<div class="container">
						<header class="major">
							<h2>OpenThrottle makes sure you get a smooth ride</h2>
							</header>
						<div class="box alt">
							<div class="row uniform">
								<section class="4u 6u(medium) 12u$(xsmall)">
									<span class="icon alt major fa-motorcycle"></span>
									<h3>YOUR MOTORCYCLE IS SAFE</h3>
									<p>Peace of mind is included with every rental. Your bike is fully insured by one of our trusted partners</p>
								</section>
								<section class="4u 6u$(medium) 12u$(xsmall)">
									<span class="icon alt major fa-comments"></span>
									<h3>24H CUSTOMER SERVICE</h3>
									<p>We are here always 365 days, 24X7. You ride, we take care of rest.</p>
								</section>
								<section class="4u$ 6u(medium) 12u$(xsmall)">
									<span class="icon alt major fa-cogs"></span>
									<h3>RELIABLE BIKES</h3>
									<p>All bikes listed on Openthrottle are reliable and safe. We ensure all bikes fit descriptions.</p>
								</section>
								<section class="4u 6u$(medium) 12u$(xsmall)">
									<span class="icon alt major fa-usd"></span>
									<h3>FIXED RATES</h3>
									<p>Once the bike is booked, rate would never change or surge. Be it a weekend, weekday or a holiday.</p>
								</section>
								<section class="4u 6u(medium) 12u$(xsmall)">
									<span class="icon alt major fa-heart"></span>
									<h3>NO MEMBERSHIP FEES</h3>
									<p>OpenThrottle is free to join. No monthly or annual fees for owners or renters.</p>
								</section>
								<section class="4u$ 6u$(medium) 12u$(xsmall)">
									<span class="icon alt major fa-lock"></span>
									<h3>YOU ARE IN CONTROL</h3>
									<p>You don't have to approve a renter unless you are 100% comfortable.</p>
								</section>
							</div>
						</div>
					</div>
				</section>

			<!-- Five -->
				
				<% if signed_in? %>
				<section id="five" class="wrapper style2 special fade">
				<div class="container">
						<header>
							<h2>Let's ride</h2>
							<p>You are part of the largest peer-to-peer motorbike sharing community in the world</p>
						</header>
						
							<div class="actions">
								<div class="actions"><div class="button"><%= link_to "My Profile", user_path(current_user.id) %></div></div>
							</div>
					</div>
					</section>
                    <%else%>
                    <section id="five" class="wrapper style2 special fade">
					<div class="container">
						<header>
							<h2>Time to get on the road</h2>
							<p>Join the largest peer-to-peer motorbike sharing community in the world</p>
						</header>
						
							<div class="actions">
								<div class="actions"><div class="button"><%= link_to 'Sign up now and find your dream ride', sign_in_path %></div></div><br>
								<div class="actions"><div class="button"><%= link_to 'Sign up with Facebook', "/auth/facebook" %></div></div>
							</div>
					</div>
					</section>
					<%end%>
			