config/routes.rb
Rails.application.routes.draw do

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  get "/log_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get 'transactions/new'

  get "mapmyride" => "vehicles#map"

  root 'welcome#index'

  get 'users/show'

  get 'users/edit'

  get 'users/update'

  get 'users/destroy'

  resources :vehicles

  resources :reservations

  resources :transactions, only: [:new, :create]

  resources :users, only: [:show, :edit, :update, :destroy]

  
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  
  get 'tags/:tag', to: 'welcome#index', as: "tag"

  get "/vehicle/payment", to: "vehicle#payment"

end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  
  has_many :vehicle_images
  has_many :taggings
  has_many :reservation
  has_many :tags, through: :taggings
  belongs_to :user
  mount_uploader :image, ImageUploader

def full_address
[address, city, country].compact.join(',')
end

  geocoded_by :full_address             # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates

  #Getter and Setter for all_tags vertial at tribute
  def all_tags=(names)
    self.tags = names.split(",").map do |name|
    Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    self.tags.map(&:name).join(", ")
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).posts
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  
  # respond_to :html, :js
  
  def new
    @vehicle = Vehicle.new
    @lastvehicle = Vehicle.last
    @vehicles = Vehicle.order(created_at: :desc).limit(16)
  end

  def create
     @vehicle = Vehicle.new(vehicle_params)

     respond_to do |format|
      if @vehicle.save 
        format.js # Will search for create.js.erb
        @lastvehicle = Vehicle.last
      else 
        format.html { render root_path }
      end 
    end
  end

  def map
    @vehicle = Vehicle.where.not(latitude: nil)
  end

  
  def index
      @vmapper = Vehicle.where.not(latitude: nil)
      @vmap = @vmapper.last

      if params[:tag]
        @vehicles = Vehicle.tagged_with(params[:tag])
      else
        @vehicles = Vehicle.all.order('created_at DESC').paginate(page: params[:page], per_page: 4)
      end
  end

  def show
     @vehicle = Vehicle.find(params[:id])
     @reservation =Reservation.new
     @user = User.find(@vehicle.user_id)
     if !Reservation.find_by_user_id_and_vehicle_id(current_user.id, @vehicle.id).nil?
     @total_price = Reservation.find_by_user_id_and_vehicle_id(current_user.id, @vehicle.id).total_price
     @beginning = Reservation.find_by_user_id_and_vehicle_id(current_user.id, @vehicle.id).check_in_date
     @end = Reservation.find_by_user_id_and_vehicle_id(current_user.id, @vehicle.id).check_out_date
     @days = (@end - @beginning).to_i
   end
     gon.client_token = generate_client_token
  end

  def update
    @vehicle = Vehicle.last
    
      if @vehicle.update(vehicle_params)

        redirect_to vehicle_path(@vehicle.id)
      else
        redirect "/"
    end
  end

  def destroy
    @vehicle = Vehicle.find(params[:id])
    @reservation = Reservation.find_by_user_id_and_vehicle_id(current_user.id, @vehicle.id)
    @cancel = @reservation.destroy
    redirect_to vehicle_path(@vehicle.id)
  end


private 
  def vehicle_params 
    params.require(:vehicle).permit(:type_vehicle, :user_id, :on_hire, :description, :ext_desc, :address, :city, :country, :min_day_rent, :max_day_rent, :price_per_day, :brand, :model, :image, :type, :model_year, :cc, :accessories, :all_tags) 
  end

def generate_client_token
  Braintree::ClientToken.generate
end

end

app/helpers/vehicle_helper.rb
module VehicleHelper
	def tag_links(tags)
	  tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(", ") 
	end
	def tag_links_button(tags)
	  tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip), {class: 'button special small'} }.join(", ") 
	end
end

app/views/vehicles/_new.html.erb
<div>

<%= form_for(@vehicle, remote: true) do |f| %>

<div>
  <%= f.label "Catchy title for your motorbike rental:" %>
  <%= f.text_field :description, placeholder: "Your rental title" %><br>
</div>

<div>
  <%= f.label "Address where your motorbike is located:" %>
  <%= f.text_field :address, placeholder: "Please enter a street address (e.g: 123 Sunset Boulevard)" %><br>
</div>

<div>
 <%= f.label "City:" %>
 <%= f.text_field :city, placeholder: "Please enter the city where the bike is located" %><br>
</div>

<div>
  <%= f.label "Country:" %>
  <%= f.country_select :country %><br>
</div>

<div>
  <%= f.label :max_day_rent, "Maximum number of days you'd be willing to rent it out:" %>
  <%= f.select :max_day_rent, ['1 day max', 'up to 2 days', 'up to 3 days', 'up to 4 days', 'up to 5 days', 'up to 6 days', 'up to 7 days', 'More than 7 days', 'More than a month']%> <br>
</div>

<div>
  <%= f.label :price_per_day, "Price per day:" %>
  <%= f.text_field :price_per_day, placeholder: "Please input only a number, in US dollars (eg: 25)" %><br><br>
 </div>

<div>
  <%= f.label "Brand:" %>
  <%= f.text_field :brand, placeholder: "Suzuki? Kawasaki? Triumph? Royal Enfield?" %><br>
</div>
 
 <div>
   <%= f.label "Model:" %>
   <%= f.text_area :model, placeholder: "Street triple? ER6-N? Bullet? Hayabusa?" %><br>
  </div>

<div>
   <%= f.label "Year of production:" %>
   <%= f.select :model_year, (Time.zone.now.year - 100)..(Time.zone.now.year + 1) %> <br>
  </div>

<div>
   <%= f.label "What type of motorbike is it?" %>
  <%= f.select :type_vehicle, ['Roadster', 'Cruiser', 'Sport Bike', 'Touring', 'Sport Touring', 'Dual Sport', 'Scooter/Moped', 'Off Road', 'Vintage']%> <br>

<div>
   <%= f.label :cc, "Your bike's CC" %>
   <%= f.select :cc, ['Up to 49cc', '50 to 124cc', '125 to 499cc', '500 to 799cc', '800 to 1199cc', '1200cc and beyond']%> <br>
</div>

<div>
    <%= f.label "Do you provide any accessories with the bike?" %>
    <%= f.text_area :accessories, placeholder: "Helmets? Goggles? Saddlebags?" %><br>
</div>

<div>
  <%= f.label "Please describe your motorbike in a few lines:" %>
  <%= f.text_area :ext_desc, placeholder: "Tell people why your bike is awesome and the thrills they are gonna get from riding it." %><br>
</div>

<div>
    <%= f.label "Tag your motorbike!" %>
    <%= f.text_field :all_tags, placeholder: "Please separate your tags with a comma. Eg: Vintage, Triumph, 1967, legendary" %>
</div>

<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden" />

<%=f.hidden_field :user_id, value: current_user.id%>

<br>
 <div id="create_vehicle">
    <%= f.submit "Click to create your rental!" %>
 </div>

</div>

<% end %>

<br>


<div id="upload_image">
<%= form_for @lastvehicle, url: vehicle_path(@lastvehicle.id) do |x| %>
    <div>
    <%= x.label :image, "Once your listing is created, you can choose an image to represent your motorbike!" %><br>
     <%= x.file_field :image %>
    </div>
    <div id="upload_image">
    <%= x.submit "Upload" %>
 </div>

<% end %>

app/views/vehicles/_vehicle.html.erb
<%= div_for vehicle do %>
  <div>
    <strong><%= link_to h(vehicle.description), vehicle_path(vehicle.id) %></strong><br />
    <span class="image left"><%=image_tag vehicle.image %></span>
    <sup>From <%= time_ago_in_words(vehicle.created_at)%></sup><br />
    <div>
      <%= h(vehicle.brand) %>
    </div>
    <div>
      <%= h(vehicle.model) %>
    </div>
    <div>
      <%= h(vehicle.cc) %>
    </div>
    <div>
      <%=raw tag_links(vehicle.all_tags) %>
    </div>
  </div>
  <br>
<% end %>

app/views/vehicles/create.html.erb
<h1>Vehicle#create</h1>
<p>Find me in app/views/vehicle/create.html.erb</p>

app/views/vehicles/create.js.erb
alert("Your new listing has been successfully created!");
var new_vehicle = $("<%= escape_javascript(render(partial: @vehicle))%>").hide();
$('#vehicles').prepend(new_vehicle);
$('#vehicle_<%= @vehicle.id %>').fadeIn('slow');
$('#new_vehicle')[0].reset();

app/views/vehicles/delete.html.erb
<h1>Vehicle#delete</h1>
<p>Find me in app/views/vehicle/delete.html.erb</p>

app/views/vehicles/index.html.erb
<!-- Main -->
  <script src='https://maps.googleapis.com/maps/api/js?v=3.exp'></script>


      <%= javascript_tag do %>

      function init_map(){

      var myOptions = {
      zoom:17,center:new google.maps.LatLng(<%= @vmap.latitude %>,<%= @vmap.longitude %>),
      mapTypeId: google.maps.MapTypeId.ROADMAP
          };

          map = new google.maps.Map(document.getElementById('gmap_canvas'), myOptions);

          marker = new google.maps.Marker({
          map: map,position: new google.maps.LatLng(<%= @vmap.latitude %>,<%= @vmap.longitude %>)
        });

        infowindow = new google.maps.InfoWindow({
        content:'<div><%= link_to @vmap.description, vehicle_path(@vmap.id), {:style=>'color:#000;'} %></div>'



      });

      google.maps.event.addListener(marker, 'click', function(){
      infowindow.open(map,marker);
      });

      infowindow.open(map,marker);}google.maps.event.addDomListener(window, 'load', init_map);

      <% end %>

<div id="main" class="wrapper style1">
  <div class="container">
    <header class="major">
      <h2>Check out the latest motorcycles for rent on OpenThrottle</h2>
      <p>Go for a ride. The road is calling.</p>
    </header>
    <div class="row 150%">
      <div class="4u 12u$(medium)">

        <!-- Sidebar -->
        <section id="sidebar">
          <section>
            <span class="image fit main"><%=image_tag "picindex.png" %></span>
            <p>Here, you'll find all the latest motorcycles posted for rent on OpenThrottle.</p>
          </section>
          <hr />
          <section>
            <h3>Latest motorbike for rent:</h3>
            <div style='overflow:hidden;height:500px;width:100%;'>
            <div id='gmap_canvas' style='height:500px;width:100%;'></div>
            <style>#gmap_canvas img{
              max-width:none!important;
              background:none!important
            }
          </style>
        </div>
            <footer>
            <br/>
              <ul class="actions">
                <li><a href="mapmyride" class="button">See all bikes on a map</a></li>
              </ul>
            </footer>
          </section>
        </section>

      </div>
      <%= will_paginate @vehicles %>
      <div class="8u$ 12u$(medium) important(medium)">
        <% @vehicles.each do |vehicle| %> 
        <!-- Content -->
        <section id="content">
          <span class="image fit"><%=image_tag vehicle.image.to_s %></span>
          <span><h6>Added: <%= vehicle.created_at %></h6></span>
          <h3><%= vehicle.description %></h3>

          <ul>
            <li><strong>Brand:</strong> <%= vehicle.brand %></li>
            <li><strong>Model:</strong> <%= vehicle.model%> </li>
            <li><strong>CC:</strong> <%= vehicle.cc%></li>
          </ul>
          <ul>
            <blockquote>Price per day: <strong>US$ <%=vehicle.price_per_day %></strong> </blockquote>
          </ul>
          <% if current_user %>
          <h3><%= button_to 'More info about this motorbike', vehicle_path(vehicle), method: "get"%></h3>
          <%else%>
          <div class="button"><%= link_to "Please sign-up to view more details about this motorcycle!", sign_up_path %></div>
          <br>
          <br>
          <%end%>
          <header class="major"></header>
        </section>
        <% end %>
      </div>
    </div>
  </div>
</div>

</section>

app/views/vehicles/map.html.erb
<script src='https://maps.googleapis.com/maps/api/js?v=3.exp'></script>


			<%= javascript_tag do %>

			function init_map(){

				var myOptions = {
					zoom:12	,center:new google.maps.LatLng(3.139003,101.686855),
					mapTypeId: google.maps.MapTypeId.ROADMAP
				};

				map = new google.maps.Map(document.getElementById('gmap_canvas'), myOptions);

				<% @vehicle.each do |v| %> 

					marker = new google.maps.Marker({
						map: map,position: new google.maps.LatLng(<%= v.latitude %>,<%= v.longitude %>)
					});


					infowindow = new google.maps.InfoWindow({
						content:'<div class="button"><%= link_to v.description, vehicle_path(v.id), {:style=>'color:#000;'} %></div>'
					});
				

					google.maps.event.addListener(marker, 'click', function(){
						infowindow.open(map,marker);
					});
					infowindow.open(map,marker);
				<% end %>
			}

			google.maps.event.addDomListener(window, 'load', init_map);

			<% end %>

<% if current_user %>

<div id="main" class="wrapper style1">
					<div class="container">
						<header class="major">
							<h2>Map My Ride</h2>
							<p>See all the motorcycles for rent in your area!</p>
							<h6>This is a <strong>beta</strong> function! Only for Kuala Lumpur area for now :)</h6>
						</header>

						<!-- Content -->
							<section id="content">
								<div style='overflow:hidden;height:800px;width:100%;'>
						<div id='gmap_canvas' style='height:800px;width:100%;'></div>
						<style>#gmap_canvas img{
							max-width:none!important;
							background:none!important
						}
					</style>
				</div>
							</section>

					</div>
				</div>

<%else%>

<div id="main" class="wrapper style1">
					<div class="container">
						<header class="major">
<h2>Map My Ride</h2>
<p>You need to be logged in to view the interactive map!</p>
<section>
<span class="image fit"><%=image_tag "mapmyridebeta.jpg" %></span>
</section>
<%end%>

app/views/vehicles/new.html.erb
<div id="main" class="wrapper style1">
          <div class="container">
            <header class="major">
              <h2>Rent your Motorbike</h2>
              <p>It's sitting in your garage, rent it out</p>
            </header>
            <div class="row 150%">
              <div class="4u 12u$(medium)">

                <!-- Sidebar -->
                  <section id="sidebar">
                    <section>
                      <h3>See the last vehicles for rent:</h3>
                      <%= render partial: @vehicles %>
                

              </div>
              <div class="8u$ 12u$(medium) important(medium)">

                <!-- Content -->
                  <section id="content">
                    <a href="#" class="image fit"><%=image_tag "picgarage.jpg" %></a>
                    <h3>Have a motorbike to rent? Create its profile here!</h3>
                    <%= render partial: "vehicles/new" %>
                    </section>

              </div>
            </div>
          </div>
        </div>

app/views/vehicles/payment.html.erb
			<!-- Main -->
			<div id="main" class="wrapper style1">
				<div class="container">
					<header class="major">
						<h2><%=@vehicle.description %></h2>
						<% if flash[:alert] %>
						<div class="alert alert-danger">
							<h3><strong>*** <%= flash[:alert] %> ***</strong></h3>
						</div>
						<% end %>
					</header>
					<div class="row 150%">
						<div class="8u 12u$(medium)">

							<!-- Content -->
							<section id="content">
								<span class="image fit"><%=image_tag @vehicle.image.to_s %></span>

								<h3>Motorbike's description:</h3>
								<p><%=@vehicle.ext_desc%></p>

								<section id="content">
									<ul>
										<blockquote>Price per day: <strong>US$ <%=@vehicle.price_per_day %></strong> </blockquote>
									</ul>
								</section>


								<h4>What's in the package?</h4>
								<ul>
									<li><strong>Brand:</strong> <%= @vehicle.brand %></li>
									<li><strong>Model:</strong> <%= @vehicle.model%> </li>
									<li><strong>Model year:</strong> <%= @vehicle.model_year%> </li>
									<li><strong>Type:</strong> <%= @vehicle.type_vehicle %></li>
									<li><strong>CC:</strong> <%= @vehicle.cc%></li>
									<li><strong>Accessories:</strong> <%= @vehicle.accessories%></li>
								</ul>
							</section>


							<section id="content">
								<h5>Max number of days you can rent the bike for: <strong><%=@vehicle.max_day_rent%></strong>.</h5>
								<br>
								<p>Tags: <%=raw tag_links_button(@vehicle.all_tags)%></p>	
							</section>
							<hr>
						</div>
						<div class="4u$ 12u$(medium)">

							<!-- Sidebar -->
							<section id="sidebar">
								<h3>Information about the owner</h3>
								<%= image_tag(@user.pic.to_s, class: "image round")%>
								<p><strong>Name:</strong> <%= @user.first_name %></p>
								<p>Sed tristique purus vitae volutpat commodo suscipit amet sed nibh. Proin a ullamcorper sed blandit.</p>
								<footer>
									<ul class="actions">
										<li><a href="#" class="button">See all this user's motorbikes</a></li>
									</ul>
								</footer>
							</section>
							<hr />
							<section>
								<h3>Where's the bike located?</h3>
								<span class="image fit"><%=image_tag "http://www.enchantehotel.com/wp-content/themes/sage/dist/images/Google-Map-Mobile.jpg" %></span>
								<ul>
									<li><strong>Country:</strong> <%=@vehicle.country %></li>
									<li><strong>City:</strong> <%=@vehicle.city %></li>
									<li><strong>Address:</strong> <%=@vehicle.address %></li>
								</ul>
							</section>
							<section>
								<h3>Other bikes nearby:</h3>
								<span class="image fit"><%=image_tag "http://www.siampod.com/wp-content/uploads/2013/07/google-map-2_07.jpg" %></span>
								<ul>
									<li><strong>Bla</strong></li>
									<li><strong>Bla</strong></li>
									<li><strong>Bla</strong></li>
								</ul>
							</section>

						</section>

					</div>
				</div>
			</div>
		</div>

app/views/vehicles/show.html.erb
			<%= include_gon %>
			<script src='https://maps.googleapis.com/maps/api/js?v=3.exp'></script>


			<%= javascript_tag do %>

			function init_map(){

			var myOptions = {
			zoom:17,center:new google.maps.LatLng(<%= @vehicle.latitude %>,<%= @vehicle.longitude %>),
			mapTypeId: google.maps.MapTypeId.ROADMAP
					};

					map = new google.maps.Map(document.getElementById('gmap_canvas'), myOptions);

					marker = new google.maps.Marker({
					map: map,position: new google.maps.LatLng(<%= @vehicle.latitude %>,<%= @vehicle.longitude %>)
				});

				infowindow = new google.maps.InfoWindow({
				content:'<div><%= link_to @vehicle.address, vehicle_path(@vehicle.id), {:style=>'color:#000;'} %></div>'



			});

			google.maps.event.addListener(marker, 'click', function(){
			infowindow.open(map,marker);
			});

			infowindow.open(map,marker);}google.maps.event.addDomListener(window, 'load', init_map);

			<% end %>


<!-- Main -->
<div id="main" class="wrapper style1">
	<div class="container">
		<header class="major">
			<h2><%=@vehicle.description %></h2>
			<% if flash[:alert] %>
			<div class="alert alert-danger">
				<h3><strong>*** <%= flash[:alert] %> ***</strong></h3>
			</div>
			<% end %>
			<% if flash[:notice] %>
			<div class="alert alert-danger">
				<h3><strong>*** <%= flash[:notice] %> ***</strong></h3>
			</div>
			<% end %>
		</header>
		<div class="row 150%">
			<div class="8u 12u$(medium)">

				<!-- Content -->
				<section id="content">
					<span class="image fit"><%=image_tag @vehicle.image.to_s %></span>

					<h3>Motorbike's description:</h3>
					<p><%=@vehicle.ext_desc%></p>

					<section id="content">
						<ul>
							<blockquote>Price per day: <strong>US$ <%=@vehicle.price_per_day %></strong> </blockquote>
						</ul>
					</section>


					<h4>What's in the package?</h4>
					<ul>
						<li><strong>Brand:</strong> <%= @vehicle.brand %></li>
						<li><strong>Model:</strong> <%= @vehicle.model%> </li>
						<li><strong>Model year:</strong> <%= @vehicle.model_year%> </li>
						<li><strong>Type:</strong> <%= @vehicle.type_vehicle %></li>
						<li><strong>CC:</strong> <%= @vehicle.cc%></li>
						<li><strong>Accessories:</strong> <%= @vehicle.accessories%></li>
					</ul>
				</section>


				<section id="content">
					<h5>Max number of days you can rent the bike for: <strong><%=@vehicle.max_day_rent%></strong>.</h5>
					<br>
					<p>Tags: <%=raw tag_links_button(@vehicle.all_tags)%></p>	
				</section>
				<hr>
				<section>

					<% if Reservation.find_by_user_id(current_user.id).nil? || Reservation.find_by_vehicle_id_and_user_id(@vehicle.id, current_user.id) == false || Reservation.find_by_vehicle_id_and_user_id(@vehicle.id, current_user.id).nil? %>

					<header class="major">
						<h2>Book this bike now!</h2>
						<p>Go for a ride.</p>
						<%= form_for @reservation do |t| %>
						<%=t.hidden_field :user_id, value: current_user.id%>
						<%=t.hidden_field :vehicle_id, value: @vehicle.id%> 
						<%= t.label :check_in_date %> 
						<%= t.date_field :check_in_date%>
						<br> 
						<br>
						<%= t.label :check_out_date %> 
						<%= t.date_field :check_out_date%>
						<br>
						<br>
						<%=t.submit "Book now!"%>
					</header>

					<%end%>

					<% else %>
					<div class="form-container radius-box glassy-bg small-10 small-centered medium-8 large-6 columns">
						<h2 class="mbs">Book this motorbike now!</h2>
						<%= form_tag transactions_path(vehicle_id: @vehicle.id) do%>
						<p>Please enter your payment details below to book this motorbike through our secure Paypal gateway:</p>
						<p> Here are the details of your booking: from <strong><%="#{@beginning}"%></strong> to <strong><%="#{@end}"%></strong>.</p>
						<p>Your will rent this motorbike for <strong><%="#{@days}"%> days.</strong></p>
						<div id="dropin"></div>

						<%=submit_tag "Pay $#{@total_price} now", class: "button mt1" %>
						<%end%>
						<%= button_to 'Cancel transaction', vehicle_path, action: "delete", method: "delete" %>

					</div>
					<%end%>
				</section>

			</div>
			<div class="4u$ 12u$(medium)">

				<!-- Sidebar -->
				<section id="sidebar">
					<h3>Information about the owner</h3>
					<%= image_tag(@user.pic.to_s, class: "image round")%>
					<p><strong>Name:</strong> <%= @user.first_name %></p>
					<footer>
						<ul class="actions">
							<li><a href="#" class="button">See all this user's motorbikes</a></li>
						</ul>
					</footer>
				</section>
				<hr />
				<section>
					<h3>Where's the bike located?</h3>
					<div style='overflow:hidden;height:500px;width:100%;'>
						<div id='gmap_canvas' style='height:500px;width:100%;'></div>
						<style>#gmap_canvas img{
							max-width:none!important;
							background:none!important
						}
					</style>
				</div>

				<ul>
					<li><strong>Country:</strong> <%=@vehicle.country %></li>
					<li><strong>City:</strong> <%=@vehicle.city %></li>
					<li><strong>Address:</strong> <%=@vehicle.address %></li>
				</ul>
			</section>
		</section>

	</div>
</div>
</div>
</div>