config/routes.rb
Rails.application.routes.draw do

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  get "/log_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get 'transactions/new'

  get "mapmyride" => "vehicles#map"

  root 'welcome#index'

  get 'users/show'

  get 'users/edit'

  get 'users/update'

  get 'users/destroy'

  resources :vehicles

  resources :reservations

  resources :transactions, only: [:new, :create]

  resources :users, only: [:show, :edit, :update, :destroy]

  
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  
  get 'tags/:tag', to: 'welcome#index', as: "tag"

  get "/vehicle/payment", to: "vehicle#payment"

end

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <title>OpenThrottle</title>
 <%= include_gon(:init => true) %>  


    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
    <!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
    <!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->

   <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => false %>
   <%= stylesheet_link_tag 'main'%>
   <%= javascript_include_tag "vendor/modernizr" %>
   <%= csrf_meta_tags %>
  </head>
  <body class="landing">
    <div id="page-wrapper">

      <!-- Header -->
        <header id="header">
          <h1 id="logo"><%= link_to 'OpenThrottle', root_path %></h1>
          <nav id="nav">
            <ul>
              <li><%= link_to 'Home', root_path %></li>
              <li>
                <%= link_to 'Show all', vehicles_path %>
                  
              </li>
              <li><a href="/mapmyride">Map My Ride</a></li>
              <li>  <% if signed_in? %>
                    <%= link_to "My Profile", user_path(current_user.id) %>
                    <ul>
                  <li>Hey <%= current_user.email %></li>
                  <li>
                    </ul>
                    <% else %>
                    <%= link_to 'Sign in', sign_in_path %>
                    <% end %>
                  </li>
              <li>  <% if signed_in? %>
                    <%= link_to 'Sign out', sign_out_path, method: :delete%>

                    <% end %>
              </li>
            </ul>
          </nav>
          <script src="https://js.braintreegateway.com/v2/braintree.js"></script>
        </header>


<%= yield %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
</body>
      <!-- Footer -->
        <footer id="footer">
          <ul class="icons">
            <li><a href="#" class="icon alt fa-twitter"><span class="label">Twitter</span></a></li>
            <li><a href="#" class="icon alt fa-facebook"><span class="label">Facebook</span></a></li>
            <li><a href="#" class="icon alt fa-linkedin"><span class="label">LinkedIn</span></a></li>
            <li><a href="#" class="icon alt fa-instagram"><span class="label">Instagram</span></a></li>
            <li><a href="#" class="icon alt fa-github"><span class="label">GitHub</span></a></li>
            <li><a href="#" class="icon alt fa-envelope"><span class="label">Email</span></a></li>
          </ul>
          <ul class="copyright">
            <li>&copy; 2016. OpenThrottle. All rights reserved.</li><li>Design & Code: <a href="http://www.benpaget.net">Ben Paget</a></li>
          </ul>
        </footer>

    </div>

    <!-- Scripts -->

<% javascript_include_tag "jquery.min.js" %>
<% javascript_include_tag "jquery.scrolly.min.js" %>
<% javascript_include_tag "jquery.dropotron.min.js" %>
<% javascript_include_tag "jquery.scrollex.min.js" %>
<% javascript_include_tag "skel.min.js" %>
<% javascript_include_tag "util.js" %>
<% javascript_include_tag "main.js" %>
</html>